### PR TITLE
Pets table and more

### PR DESCRIPTION
**Pull request by Jeremyflc**
I added a table showing the minimum pet level required to battle in each location on the map.

### CODE REVIEW

**Review by GalahadXVI — APPROVED** [review]
Thanks for your contribution!

**Comment by GalahadXVI** [comment]
@Jeremyflc Hi. Please re-open as I didn't merge with the main branch. I only approved the changes. I merge them when they are ready to be compiled in an update.

**Comment by Jeremyflc** [comment]
Hey, @GalahadXVI I have reopened it, I will also add more.

**Review by GalahadXVI — APPROVED** [review]
Thank you for your contribution.

**Pull request merged**
